apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookstore-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bookstore
  template:
    metadata:
      labels:
        app: bookstore
    spec:
      containers:
      - name: bookstore
        image: krishna2317/onlinebookstore:try
        ports:
        - containerPort: 8081  # Change containerPort to 8081
        env:
        - name: CATALINA_OPTS
          value: "-Djava.security.egd=file:/dev/./urandom -Dserver.port=8081"  # Change the server port
